[package]
name = "services"
edition = { workspace = true }
version = { workspace = true }

[dependencies]
chrono = { workspace = true }
cacher = { path = "../cacher" }
chain_providers = { path = "../chain_providers" }
coingecko = { path = "../coingecko" }
config_keys = { path = "../config_keys" }
defi = { path = "../defi" }
futures = { workspace = true }
gem_client = { path = "../gem_client", features = ["reqwest"] }
lists = { path = "../lists" }
number_formatter = { path = "../number_formatter" }
primitives = { path = "../primitives" }
pusher = { path = "../pusher" }
search_index = { path = "../search_index" }
serde = { workspace = true }
settings = { path = "../settings" }
storage = { path = "../storage" }
streamer = { path = "../streamer" }
